In [168]:
import numpy as np
from numpy import random as r

a = r.uniform(size=(2,3)).reshape((2, 1, 3))
b = np.zeros(shape=(2,4,3))
print(a)
print(b)
a+b

[[[0.79006367 0.23812604 0.61326352]]

 [[0.83184198 0.67552404 0.67135929]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


array([[[0.79006367, 0.23812604, 0.61326352],
        [0.79006367, 0.23812604, 0.61326352],
        [0.79006367, 0.23812604, 0.61326352],
        [0.79006367, 0.23812604, 0.61326352]],

       [[0.83184198, 0.67552404, 0.67135929],
        [0.83184198, 0.67552404, 0.67135929],
        [0.83184198, 0.67552404, 0.67135929],
        [0.83184198, 0.67552404, 0.67135929]]])